### ISSUE TITLE
Docs aren't rendered for the default export when there are other exports in the same file

### ISSUE THREAD

**Issue by binomialstew** [storybooks/babel-plugin-react-docgen#40]
This seems to be related to [this issue](https://github.com/storybooks/babel-plugin-react-docgen/issues/14), but I'm opening this since that was closed over a 6 months ago.

I see that when exporting multiple components from a single file. Docs aren't rendered at all—even for the default exported component. Based on the comments above, it seems the expected behavior would be that docs are rendered the default export only, but no docs are rendered.

This can be tested by exporting a component in addition to the default export. For example, in `test/fixtures/case5/actual.js`:
```js
import React, { PropTypes } from 'react'

export const Second = () => (
  <div>Sample</div>
)

const First = ({ children }) => (
  <div>
    { children }
    <Second />
  </div>
)

First.propTypes = {
  children: PropTypes.node
}

export default First
```

Note the `export const Second`

In this case, `First.__docgenInfo` does not exist.

**Comment by danielduan** [comment]
I can see how it's possible. Feel free to open a PR if you'd like to tackle the issue, I'd really appreciate it.

I think a workaround would be to use `findAllExportedComponentDefinitions` for the `resolver` option.

**Comment by CLL80** [comment]
Thanks for the hint. I'll see if I can set aside some time for this.

**Comment by CLL80** [comment]
PR [here](https://github.com/storybooks/babel-plugin-react-docgen/pull/46). When using the `findAllExportedComponentDefinitions` resolver, the docgenInfo is an array with the object inside. This is not usable by `@storybook/addon-info` in it's current state because it is looking for an object directly inside `__docgenInfo`. If it is not found, no docs are rendered for `react-docgen`.
